controllers-my-bundle:
    resource: ../../src-my-bundle/Controller/
    type: annotation

controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
